# Generated by Django 3.2.24 on 2024-12-26 04:39

import datetime
import deepgis_xr.apps.core.models
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='unknown', max_length=100, unique=True)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('label_type', models.CharField(choices=[('R', 'Rectangle'), ('C', 'Circle'), ('P', 'Polygon'), ('A', 'Any')], default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('width', models.PositiveSmallIntegerField(default=1920)),
                ('height', models.PositiveSmallIntegerField(default=1080)),
                ('categories', models.ManyToManyField(to='core.CategoryType')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='unknown', max_length=200, unique=True)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Labeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labelers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RasterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, unique=True)),
                ('path', models.CharField(max_length=5000)),
                ('attribution', models.CharField(max_length=5000)),
                ('min_zoom', models.FloatField()),
                ('max_zoom', models.FloatField()),
                ('resolution', models.FloatField(default=-1)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TiledGISLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('northeast_lat', models.DecimalField(decimal_places=14, max_digits=17)),
                ('northeast_lng', models.DecimalField(decimal_places=14, max_digits=17)),
                ('southwest_lat', models.DecimalField(decimal_places=14, max_digits=17)),
                ('southwest_lng', models.DecimalField(decimal_places=14, max_digits=17)),
                ('zoom_level', models.PositiveSmallIntegerField(default=23)),
                ('label_json', models.JSONField()),
                ('label_type', models.CharField(choices=[('R', 'Rectangle'), ('C', 'Circle'), ('P', 'Polygon'), ('A', 'Any')], default='R', max_length=1)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categorytype')),
                ('labeler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.labeler')),
                ('parent_raster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rasterimage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
            ],
            options={
                'unique_together': {('x', 'y', 'width', 'height')},
            },
        ),
        migrations.CreateModel(
            name='ImageLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combined_label_shapes', models.TextField(max_length=100000)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('time_taken', models.PositiveIntegerField(null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.image')),
                ('labeler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.labeler')),
                ('window', models.ForeignKey(default=deepgis_xr.apps.core.models.get_default_window, on_delete=django.db.models.deletion.CASCADE, to='core.imagewindow')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brightness', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
                ('contrast', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
                ('saturation', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
                ('image_label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.imagelabel')),
                ('labeler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.labeler')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagesourcetype'),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)])),
                ('green', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)])),
                ('blue', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)])),
            ],
            options={
                'unique_together': {('red', 'green', 'blue')},
            },
        ),
        migrations.AddField(
            model_name='categorytype',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.color'),
        ),
        migrations.CreateModel(
            name='CategoryLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_shapes', models.TextField(max_length=100000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorytype')),
                ('parent_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagelabel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('name', 'path')},
        ),
    ]
